# Generated by Django 6.0.4 on 2026-04-17 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('is_forum', models.BooleanField(default=False)),
                ('link_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.telegramchat')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
            ],
            options={
                'unique_together': {('chat', 'thread_id')},
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_msg_id', models.BigIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramchat')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_at', models.DateTimeField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('source_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.message')),
                ('participants', models.ManyToManyField(blank=True, to='core.telegramuser')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Участник'), ('manager', 'Менеджер'), ('admin', 'Админ')], max_length=50)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramchat')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'В работе'), ('done', 'Выполнено'), ('cancelled', 'Отменено')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.message')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramuser')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['assignee', 'status'], name='core_task_assigne_c4dd42_idx'), models.Index(fields=['topic', 'status'], name='core_task_topic_i_61c6d8_idx'), models.Index(fields=['due_date', 'status'], name='core_task_due_dat_3cc367_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'topic', '-timestamp'], name='core_messag_chat_id_d9fbea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_processed', 'timestamp'], name='core_messag_is_proc_87a0a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('chat', 'topic', 'telegram_msg_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'chat')},
        ),
    ]
