# Generated by Django 6.0.4 on 2026-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskassignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('rescheduled', 'Перенесена')], default='active', max_length=20),
        ),
    ]
