# Generated by Django 6.0.4 on 2026-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='daily_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='daily_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
