# Generated by Django 6.0.4 on 2026-07-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meeting_daily_reminder_sent_task_daily_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to='core.telegramuser'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='core.telegramuser'),
        ),
    ]
