# Generated by Django 6.0.4 on 2026-07-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_meeting_creator_task_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_all_hands',
            field=models.BooleanField(default=False, help_text='True, если встреча для всех участников чата', verbose_name='Все участники'),
        ),
    ]
