# Generated by Django 6.0.4 on 2026-07-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False, help_text='True = задача-шаблон для повторяющейся серии', verbose_name='Шаблон серии'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_group_id',
            field=models.UUIDField(blank=True, help_text='Все задачи одной серии имеют одинаковый group_id', null=True, verbose_name='ID группы повторений'),
        ),
        migrations.CreateModel(
            name='MeetingRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('cron_expression', models.CharField(help_text="Пример: '0 10 * * 1' — каждый понедельник в 10:00", max_length=100, verbose_name='Cron-выражение')),
                ('human_readable', models.CharField(blank=True, default='', help_text="Пример: 'каждый понедельник в 10:00'", max_length=255, verbose_name='Человекочитаемое описание')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Длительность (мин)')),
                ('is_all_hands', models.BooleanField(default=False, verbose_name='Для всех участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramuser', verbose_name='Создатель')),
                ('source_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.message', verbose_name='Исходное сообщение')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic', verbose_name='Топик')),
            ],
            options={
                'verbose_name': 'Серия встреч',
                'verbose_name_plural': 'Серии встреч',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='core.meetingrecurrence', verbose_name='Серия повторений'),
        ),
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expression', models.CharField(help_text="Пример: '0 18 * * 5' — каждая пятница в 18:00", max_length=100, verbose_name='Cron-выражение')),
                ('human_readable', models.CharField(blank=True, default='', help_text="Пример: 'каждую пятницу в 18:00'", max_length=255, verbose_name='Человекочитаемое описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('next_occurrence', models.DateTimeField(verbose_name='Следующее выполнение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='core.task', verbose_name='Задача-шаблон')),
            ],
            options={
                'verbose_name': 'Повторение задачи',
                'verbose_name_plural': 'Повторения задач',
                'ordering': ['-next_occurrence'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRecurrenceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='core.meetingrecurrence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Участник серии встреч',
                'verbose_name_plural': 'Участники серий встреч',
                'unique_together': {('recurring_meeting', 'user')},
            },
        ),
    ]
