# Generated by Django 6.0.4 on 2026-07-23 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_is_template_task_recurrence_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period1_start', models.DateTimeField()),
                ('period1_end', models.DateTimeField()),
                ('period2_start', models.DateTimeField()),
                ('period2_end', models.DateTimeField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('topic', 'period_start', 'period_end'), name='unique_summary_period'),
        ),
        migrations.AddField(
            model_name='comparisonsummary',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
        migrations.AddConstraint(
            model_name='comparisonsummary',
            constraint=models.UniqueConstraint(fields=('topic', 'period1_start', 'period1_end', 'period2_start', 'period2_end'), name='unique_comparison_periods'),
        ),
    ]
