# Generated by Django 6.0.4 on 2026-07-27 03:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_is_template_task_recurrence_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_reminder_minutes', models.IntegerField(choices=[(15, '15 минут'), (60, '1 час'), (1440, '1 день')], default=60, verbose_name='Напоминание о встрече')),
                ('digest_time', models.TimeField(blank=True, default=datetime.time(9, 0), null=True, verbose_name='Время дайджеста')),
                ('digest_enabled', models.BooleanField(default=True, verbose_name='Дайджест включён')),
                ('task_reminder_enabled', models.BooleanField(default=True, verbose_name='Напоминания о задачах')),
                ('meeting_reminder_enabled', models.BooleanField(default=True, verbose_name='Напоминания о встречах')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_settings', to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
