# Generated by Django 6.0.4 on 2026-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('critical', '🔴 Критический'), ('high', '🟡 Высокий'), ('normal', '🟢 Средний'), ('low', '⚪ Низкий')], default='normal', max_length=20, verbose_name='Приоритет'),
        ),
    ]
