# Generated by Django 6.0.4 on 2026-07-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('assignees', models.ManyToManyField(blank=True, related_name='subtask_assignments', to='core.telegramuser', verbose_name='Исполнители')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.task', verbose_name='Родительская задача')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'ordering': ['order', 'id'],
            },
        ),
    ]
