# Generated by Django 6.0.4 on 2026-08-25 12:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='quiet_end',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Конец тихих часов'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=True, verbose_name='Тихие часы включены'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='quiet_start',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Начало тихих часов'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='skip_weekends',
            field=models.BooleanField(default=True, verbose_name='Не беспокоить в выходные'),
        ),
        migrations.CreateModel(
            name='PendingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task', 'Задача'), ('meeting', 'Встреча')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_assignments', to='core.meeting')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_assignments', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_assignments', to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Отложенное назначение',
                'verbose_name_plural': 'Отложенные назначения',
            },
        ),
        migrations.CreateModel(
            name='UserAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало недоступности')),
                ('end', models.DateTimeField(verbose_name='Конец недоступности')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Недоступность пользователя',
                'verbose_name_plural': 'Недоступности пользователей',
                'indexes': [models.Index(fields=['user', 'start', 'end'], name='core_userab_user_id_e5ddcb_idx'), models.Index(fields=['end'], name='core_userab_end_3e6a77_idx')],
            },
        ),
    ]
