# Generated by Django 6.0.4 on 2026-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usernotificationsettings_quiet_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
